name: Pull Requests
on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.go'
      - 'go.mod'
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        go version
        go mod download
    - name: Run Test
      run: |
        go test -count=10 ./...
  lint:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        go install golang.org/x/lint/golint@latest
        go mod download
    - name: Run Lint
      run: |
        golint -set_exit_status=1 ./...
  release_check:  
    runs-on: ubuntu-latest
    outputs:
      git_diff: ${{ steps.output.outputs.git_diff }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check Diff
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.go
            !**/*_test.go
          FILES: |
            go.mod
      - name: Output Diff
        id: output
        if: env.GIT_DIFF
        run: |
          echo "::set-output name=git_diff::${{ env.GIT_DIFF }}"
  release:
    runs-on: ubuntu-latest
    needs: [release_check]
    if: ${{ needs.release_check.outputs.git_diff }}
    steps:
      - name: output
        run: |
          echo "${{ needs.release_check.outputs.git_diff }}";
          echo "This pull request will create a release"
