name: Pull Requests
on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - '**.go'
      - 'go.mod'
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        go version
        go mod download
    - name: Run Test
      run: |
        go test -v -count=10 ./...
  lint:
    strategy:
      matrix:
        go-version: [1.17.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        go install golang.org/x/lint/golint@latest
        go mod download
    - name: Run Lint
      run: |
        golint -set_exit_status=1 ./...
  release_check:  
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Diff
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            +**/*.go
            !**/*_test.go
          FILES: |
            go.mod
      - name: Output Diff
        if: env.GIT_DIFF
        run: |
          echo ${{ env.GIT_DIFF }}
