name: Manual Release Build
on: 
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        goversion: ["1.17"]
        exclude:  
          - goarch: "386"
            goos: darwin 
          - goarch: "386"
            goos: windows
          - goarch: arm64
            goos: windows 
    steps:
    - uses: actions/checkout@v3
    - name: Set BUILD_VERSION env
      run: echo "RELEASE_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
    - uses: wangyoucao577/go-release-action@v1.36
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: ${{ matrix.goversion }}
        project_path: "./cmd/"
        binary_name: "jsonpath"
        overwrite: true
        ldflags: -X "main.Command=jsonpath" -X "main.Version=${{ env.RELEASE_TAG }}" -X "main.OS=${{ matrix.goos }}" -X "main.Arch=${{ matrix.goarch }}"
